#Entry
input = Entry(width=10)
input.grid(column=1,row=0)
print(input.get())
label= Label(text="Miles", font=("Arial",20))
label.grid(column=2,row=0)
label_1=Label(text="is equal to", font=("Arial",20))
label_1.grid(column=0,row=1)
label_res = Label(text="0", font=("Arial",20))
label_res.grid(column=1,row=1)
label_2=Label(text="Km", font=("Arial",20))
label_2.grid(column=2,row=1)
new_button = Button(text="Calculate",command=miles_to_Km)
new_button.grid(column=1,row=2)
